### ISSUE TITLE
Attach Detach refactoring

### ISSUE THREAD

**Issue by aswarke** [IBM/ubiquity-docker-plugin#12] opened 2017-06-09 21:58 UTC
Incorporating changes from Ubiquity Refactoring (ibm/ubiquity#31)

**Comment by midoblgsm** [comment] 2017-06-12 16:41
I am closing this since it is a duplicate of #13

**Comment by aswarke** [comment] 2017-06-13 22:25
@midoblgsm this is an issue that was linked to pull request #13  . I was attempting to connect an issue with an pull request to address the issue

**Closed as completed** 2017-06-14 21:18 UTC
Labels: enhancement
